#!/bin/sh
set -e
PROJECT_ROOT=`dirname "$0"`/../
# build and lint the project
${PROJECT_ROOT}/bin/build.sh
${PROJECT_ROOT}/bin/lint.sh
# add build directories
git add ${PROJECT_ROOT}/docs/
git add ${PROJECT_ROOT}/permon/frontend/browser/dist/